trigger:
- main

pool: default

variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    corepack enable
    corepack prepare pnpm@latest-9 --activate
    pnpm config set store-dir $(pnpm_config_cache)
  displayName: "Configure pnpm corepack"

- script: |
    pnpm install webpack webpack-cli @types/node --save-dev
    pnpm exec webpack --mode development
    pnpm pack --pack-destination dist
  displayName: 'PNPM Install and Run webpack'
  workingDirectory: $(Build.SourcesDirectory)/orders-module

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       orders-module/dist/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: Order-SDK
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish to artifacts'

- task: Npm@1
  displayName: 'Publish to registry'
  inputs:
   command: publish --access=restricted
   publishRegistry: useFeed
   publishFeed: Internal
   workingDir: $(Build.SourcesDirectory)/orders-module
   
